services:
  superset:
    image: apache/superset:latest
    
    ports:
      - "8288:8088"
    environment:
      - SUPERSET_SECRET_KEY=xG0kRUVZXaNQcOMiDYZ8gMaVjKcTcxksHbm5eQOAbXk
      - SUPERSET_FEATURE_EMBEDDED_SUPERSET=true
      - SUPERSET_ADMIN_USERNAME=admin
      - SUPERSET_ADMIN_FIRST_NAME=Superset
      - SUPERSET_ADMIN_LAST_NAME=Admin
      - SUPERSET_ADMIN_EMAIL=admin@superset.com
      - SUPERSET_ADMIN_PASSWORD=admin
    volumes:
      - ./superset_config:/app/pythonpath
    
    command: >
      sh -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Superset --lastname Admin --email admin@superset.com --password admin &&
        superset init &&
        superset run -p 8088 --host=0.0.0.0
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/health"]
      interval: 30s
      timeout: 10s
      retries: 5